### ISSUE TITLE
Add Mini doesn't always work

### ISSUE THREAD

**Issue by richardwolny** [AsherGlick/Superposition#5]
The reason is that the random numbers generated by each client and the server use the same sequence. The randomize() function needs to be called to change the seed.

This brings up the question of how to assign ID's to entities so that we can correctly identify them across the network. With random numbers, it is still possible for ID collisions between two different peers. It is even possible within the same peer. Using a properly seeded generated just reduces the chance of this.

I propose doing a couple of things.
1.) Let the server be the master when it comes to assigning ID's.
2.) Use unique identifiers for entities (mini, circle, etc..).
2a.) Create an incrementing value that will always assign a different id whenever we create an 
2b.) Leverage the instance id/name that Godot assigns when you add a child to the Scene Graph. Godot will already number each child uniquely. It starts with 3 digits like "hero@150" but when you get passes 999 it uses 4 digits.

**Comment by richardwolny** [comment]
I created a branch which fixes this bug: https://github.com/richardwolny/Superposition/tree/create-mini-bug

The approach I am taking is by splitting the mini creation into 2 steps. Clients request the server for a mini (master annotation), sending all of the previous arguments excluding the ID. The server then generates the ID and calls create_mini for itself and each client (remotesync annotation).

This does add a slight delay from the client clicking create, and the mini showing up. Before it was instantaneous. I have iterated through many approaches for this. I think there is a way to give us unique ID's and instantaneous creation (from the clients perspective). It involves each client assigning there own ID and sending it to the server. On the server, we maintain a separate list of ID's for each client, or a single list where we append the peer id to the entity id. This is a little more work so I propose that we do the simpler slightly slower way first.

**Comment by AsherGlick** [comment]
Fantastic discovery

1) For no good technical reason other then ease of programming I want to avoid having to rely on the server for things like this. I could be easily convinced otherwise
2) Probably a good start
2a.) This is not that much different from using the seeded random numbers without change 1
2b.) I am not sure the instance name is trustworthy, it might be but I would not leave it up to a system that may change, it is also what is used for determining which target the RPC should be called on for a client so if ids got out of sync a character would be movable on one display but be static on another.


3) One of the ideas I want to implement is "Factions" which allow groups of minis to share vision with their controllers and other groups of minis to not share vision. This will necessitate some information being exchanged between the server and client on connect. An additional piece of information that could be passed is a random seed which can be stuck in a random number generator specifically allocated for character ID generation: https://docs.godotengine.org/en/stable/classes/class_randomnumbergenerator.html . Though this is unlikely to have a race condition or issue if it does it will act as if the minis just cant be generated because the number of ids that will conflict may be great, this is unlikely to be a real concern.

4) You could also achieve something similar by calling `.randomize()` on the client when it connects and not worry about syncing numbers form the server, or call .randomize() before each call to create mini though I dont know how slow it is. Calling randomize only on connect may be the easiest to implement but could possibly have race conditions if all the clients were polling for the server to appear and all connected simultaneously.

5) My third option would be to scan all ids in the minis list if an id already exists then use a different one. This option guarantees a mini can be created but requires additional logic each time the create mini rpc is called and cannot be shared inside the function itself. A wrapper could be used that did this work and then internally called the rpc.

6) Similar to 3 a simple prefix could be randomized by the server and shared with each client on connect. The prefix would be added to each id outside of the create mini function making it so that each client will always generate unique ids from each other.

**Comment by richardwolny** [comment]
To summarize what I did in #6 

Your option number 6 solves the issue in the simplest way possible. The unique "prefix" you mention is already done by Godot in the form of the peer network id. Each client knows its own network id. This combined with the fact that each peer can already create unique path names for its own Scene Tree, means we can pretty easily guarantee a unique name for all peers.
